In [7]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Input

In [2]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
    ]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot('amazing restaurant', 30)

[9, 11]

In [4]:
encoded_reviews = [one_hot(elem, 30) for elem in reviews]
encoded_reviews

[[1, 14],
 [9, 11],
 [24, 20],
 [7, 15, 14],
 [9, 25, 28],
 [29, 14],
 [8, 25, 6],
 [27, 16],
 [27, 7],
 [3, 29]]

In [5]:
padded_reviews = pad_sequences(encoded_reviews, maxlen=3, padding='post')
padded_reviews

array([[ 1, 14,  0],
       [ 9, 11,  0],
       [24, 20,  0],
       [ 7, 15, 14],
       [ 9, 25, 28],
       [29, 14,  0],
       [ 8, 25,  6],
       [27, 16,  0],
       [27,  7,  0],
       [ 3, 29,  0]])

In [8]:
vocab_size = 30
pad_length = 3
vector_size = 5

model = Sequential()
model.add(Input(shape=(pad_length,)))
model.add(Embedding(vocab_size, vector_size, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [10]:
X = padded_reviews
y = sentiment

In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 3, 5)           │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 15)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 166 (664.00 B)

 Trainable params: 166 (664.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.fit(X, y, epochs=50, verbose=0)

In [13]:
model.evaluate(X, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 1.0000 - loss: 0.6097


[0.609734058380127, 1.0]

In [16]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [17]:
weights[1], weights[9]

(array([ 0.03571736, -0.04436741, -0.0883772 ,  0.06227136, -0.02012075],
       dtype=float32),
 array([ 0.05738758, -0.04833527, -0.08841626,  0.02376203, -0.02412082],
       dtype=float32))